"""Deterministic, resumable Cartesian strategy optimization."""

from quantforge.optimization.combinations import (
    CombinationExclusion,
    ParameterCombination,
    iter_combination_candidates,
)
from quantforge.optimization.constraints import (
    ComparisonOperator,
    CustomParameterConstraint,
    ParameterAtMost,
    ParameterComparison,
    ParameterConstraint,
    ParameterLessThan,
)
from quantforge.optimization.errors import (
    CombinationLimitExceededError,
    InvalidSearchSpaceError,
    InvalidStudyConfigurationError,
    OptimizationError,
    RankingError,
    StudyExecutionError,
    StudyPersistenceError,
)
from quantforge.optimization.export import export_study_result
from quantforge.optimization.factories import (
    MovingAverageCrossoverFactory,
    StrategyFactory,
)
from quantforge.optimization.models import (
    ExecutionConfig,
    ExecutionMode,
    FilePersistenceConfig,
    GridSearchConfig,
    HardMetricConstraint,
    IneligibleTrial,
    MaximumDrawdown,
    MetricName,
    MetricThreshold,
    MetricTieBreaker,
    MinimumTrades,
    ParameterSummary,
    PositiveReturn,
    RankedTrial,
    RankingConfig,
    RankingDirection,
    StabilityClassification,
    StabilityConfig,
    StabilitySummary,
    StudyResult,
    ThresholdOperator,
    TrialRecord,
    TrialStatus,
    UndefinedMetricPolicy,
)
from quantforge.optimization.ranking import RankingOutcome, rank_trials
from quantforge.optimization.spaces import (
    BooleanValues,
    CategoricalValues,
    FloatValues,
    IntegerValues,
    ParameterSearchSpace,
    ParameterValues,
)
from quantforge.optimization.stability import StabilityOutcome, analyze_stability
from quantforge.optimization.study import GridSearchStudy

__all__ = [
    "BooleanValues",
    "CategoricalValues",
    "CombinationExclusion",
    "CombinationLimitExceededError",
    "ComparisonOperator",
    "CustomParameterConstraint",
    "ExecutionConfig",
    "ExecutionMode",
    "FilePersistenceConfig",
    "FloatValues",
    "GridSearchConfig",
    "GridSearchStudy",
    "HardMetricConstraint",
    "IneligibleTrial",
    "IntegerValues",
    "InvalidSearchSpaceError",
    "InvalidStudyConfigurationError",
    "MaximumDrawdown",
    "MetricName",
    "MetricThreshold",
    "MetricTieBreaker",
    "MinimumTrades",
    "MovingAverageCrossoverFactory",
    "OptimizationError",
    "ParameterAtMost",
    "ParameterCombination",
    "ParameterComparison",
    "ParameterConstraint",
    "ParameterLessThan",
    "ParameterSearchSpace",
    "ParameterSummary",
    "ParameterValues",
    "PositiveReturn",
    "RankedTrial",
    "RankingConfig",
    "RankingDirection",
    "RankingError",
    "RankingOutcome",
    "StabilityClassification",
    "StabilityConfig",
    "StabilityOutcome",
    "StabilitySummary",
    "StrategyFactory",
    "StudyExecutionError",
    "StudyPersistenceError",
    "StudyResult",
    "ThresholdOperator",
    "TrialRecord",
    "TrialStatus",
    "UndefinedMetricPolicy",
    "analyze_stability",
    "export_study_result",
    "iter_combination_candidates",
    "rank_trials",
]
