"""Deterministic long-only daily-bar backtesting."""

from quantforge.backtesting.config import (
    ENGINE_VERSION,
    RESULT_SCHEMA_VERSION,
    BacktestConfig,
    DiscreteTargetWeightSizing,
    DividendPolicy,
    NextSessionOpenExecution,
    SplitAccountingPolicy,
)
from quantforge.backtesting.costs import (
    BasisPointCommission,
    BasisPointFees,
    BasisPointSlippage,
    CommissionModel,
    ExplicitZeroFees,
    FeeModel,
    FixedCommission,
    OrderSide,
    PerShareCommission,
    SlippageModel,
)
from quantforge.backtesting.errors import (
    BacktestError,
    ExecutionError,
    InvalidBacktestConfigurationError,
    InvalidMarketDataError,
    InvalidSignalError,
    PortfolioAccountingError,
    ResultExportError,
)
from quantforge.backtesting.export import (
    export_backtest_result,
    load_backtest_manifest,
)
from quantforge.backtesting.metrics import CALENDAR_DAYS_PER_YEAR
from quantforge.backtesting.models import (
    BacktestResult,
    BenchmarkResult,
    DailyPortfolioRecord,
    DividendAccountingSummary,
    DividendCashflowRecord,
    FillRecord,
    MarketDataMetadata,
    OrderRecord,
    OrderStatus,
    PerformanceSummary,
    PositionRecord,
    ReturnBasis,
    SignalRecord,
    SplitAdjustmentRecord,
    TradeRecord,
)
from quantforge.backtesting.runner import fingerprint_market_bars, run_backtest

__all__ = [
    "CALENDAR_DAYS_PER_YEAR",
    "ENGINE_VERSION",
    "RESULT_SCHEMA_VERSION",
    "BacktestConfig",
    "BacktestError",
    "BacktestResult",
    "BasisPointCommission",
    "BasisPointFees",
    "BasisPointSlippage",
    "BenchmarkResult",
    "CommissionModel",
    "DailyPortfolioRecord",
    "DiscreteTargetWeightSizing",
    "DividendAccountingSummary",
    "DividendCashflowRecord",
    "DividendPolicy",
    "ExecutionError",
    "ExplicitZeroFees",
    "FeeModel",
    "FillRecord",
    "FixedCommission",
    "InvalidBacktestConfigurationError",
    "InvalidMarketDataError",
    "InvalidSignalError",
    "MarketDataMetadata",
    "NextSessionOpenExecution",
    "OrderRecord",
    "OrderSide",
    "OrderStatus",
    "PerShareCommission",
    "PerformanceSummary",
    "PortfolioAccountingError",
    "PositionRecord",
    "ResultExportError",
    "ReturnBasis",
    "SignalRecord",
    "SlippageModel",
    "SplitAccountingPolicy",
    "SplitAdjustmentRecord",
    "TradeRecord",
    "export_backtest_result",
    "fingerprint_market_bars",
    "load_backtest_manifest",
    "run_backtest",
]
